/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ascensor;
import javax.swing.ImageIcon;
/**
 *
 * @author Usuario
 */
public class View extends javax.swing.JFrame {
    ImageIcon imageAscensorOpen= new ImageIcon("ascOpen.png");
    ImageIcon imageAscensorClosed= new ImageIcon("ascClosed.png");
    
    /**
     * Creates new form Interaze
     */
    public View(Main p) {
        this.prog = p;
        initComponents();
    }
    
     public void mostrar() {
        this.pack();
        this.setVisible(true);
        try {
            Thread.sleep(500);
        } catch (Exception e) {
        }
        this.revalidate();
        this.repaint();
    }
     
     public void notificar(String s) {
        switch(s) {
            case "BajarPiso":
                //Desplazar el ascensor abajo
                break;
            case "SubirPiso":
                //Desplazar el ascensor arriba
                break;
            case "AbrirPuerta":
                //Abrir la puerta
                break;
            case "CerrarPuerta":
                //Cerrar la puerta
                break;
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exterior = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        ediIzq = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        sub3 = new javax.swing.JButton();
        tercero = new javax.swing.JLabel();
        segundo = new javax.swing.JLabel();
        primero = new javax.swing.JLabel();
        bajo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        sub2 = new javax.swing.JButton();
        sub1 = new javax.swing.JButton();
        subB = new javax.swing.JButton();
        subTercero = new javax.swing.JLabel();
        subSegundo = new javax.swing.JLabel();
        subPrimero = new javax.swing.JLabel();
        subBajo = new javax.swing.JLabel();
        ediDer = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        baj1 = new javax.swing.JButton();
        baj2 = new javax.swing.JButton();
        baj3 = new javax.swing.JButton();
        baj4 = new javax.swing.JButton();
        bajCuarto = new javax.swing.JLabel();
        bajtercero = new javax.swing.JLabel();
        bajSegundo = new javax.swing.JLabel();
        bajPrimero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(135, 206, 235));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exterior.setBackground(new java.awt.Color(0, 32, 255));

        fondo.setBackground(new java.awt.Color(0, 0, 0));

        ediIzq.setBackground(new java.awt.Color(255, 255, 204));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));

        sub3.setText("S");
        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });

        tercero.setText("  3º");

        segundo.setText(" 2º");

        primero.setText(" 1º");

        bajo.setText(" Bajo");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setText("4º");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        sub2.setText("S");
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });

        sub1.setText("S");
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });

        subB.setText("S");
        subB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBActionPerformed(evt);
            }
        });

        subTercero.setText("jLabel6");

        subSegundo.setText("jLabel7");

        subPrimero.setText("jLabel8");

        subBajo.setText("jLabel9");

        javax.swing.GroupLayout ediIzqLayout = new javax.swing.GroupLayout(ediIzq);
        ediIzq.setLayout(ediIzqLayout);
        ediIzqLayout.setHorizontalGroup(
            ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator14)
            .addComponent(jSeparator15)
            .addGroup(ediIzqLayout.createSequentialGroup()
                .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(segundo)
                    .addComponent(primero))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(ediIzqLayout.createSequentialGroup()
                .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ediIzqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ediIzqLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediIzqLayout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addComponent(subTercero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediIzqLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediIzqLayout.createSequentialGroup()
                                .addComponent(subPrimero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediIzqLayout.createSequentialGroup()
                                .addComponent(subSegundo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediIzqLayout.createSequentialGroup()
                                .addComponent(subBajo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subB))))
                    .addGroup(ediIzqLayout.createSequentialGroup()
                        .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tercero)
                            .addComponent(bajo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ediIzqLayout.setVerticalGroup(
            ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(86, 86, 86)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tercero)
                .addGap(42, 42, 42)
                .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub3)
                    .addComponent(subTercero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(segundo)
                .addGap(45, 45, 45)
                .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub2)
                    .addComponent(subSegundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(primero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub1)
                    .addComponent(subPrimero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bajo)
                .addGap(37, 37, 37)
                .addGroup(ediIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subB)
                    .addComponent(subBajo))
                .addContainerGap())
        );

        ediDer.setBackground(new java.awt.Color(255, 255, 204));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setMinimumSize(new java.awt.Dimension(50, 11));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        baj1.setText("B");
        baj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baj1ActionPerformed(evt);
            }
        });

        baj2.setText("B");
        baj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baj2ActionPerformed(evt);
            }
        });

        baj3.setText("B");
        baj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baj3ActionPerformed(evt);
            }
        });

        baj4.setText("B");
        baj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baj4ActionPerformed(evt);
            }
        });

        bajCuarto.setText("jLabel11");

        bajtercero.setText("jLabel12");

        bajSegundo.setText("jLabel13");

        bajPrimero.setText("jLabel14");

        javax.swing.GroupLayout ediDerLayout = new javax.swing.GroupLayout(ediDer);
        ediDer.setLayout(ediDerLayout);
        ediDerLayout.setHorizontalGroup(
            ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator17)
            .addGroup(ediDerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ediDerLayout.createSequentialGroup()
                        .addComponent(baj1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bajPrimero))
                    .addGroup(ediDerLayout.createSequentialGroup()
                        .addComponent(baj2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bajSegundo))
                    .addGroup(ediDerLayout.createSequentialGroup()
                        .addComponent(baj3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bajtercero))
                    .addGroup(ediDerLayout.createSequentialGroup()
                        .addComponent(baj4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bajCuarto)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        ediDerLayout.setVerticalGroup(
            ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ediDerLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baj4)
                    .addComponent(bajCuarto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baj3)
                    .addComponent(bajtercero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baj2)
                    .addComponent(bajSegundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ediDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baj1)
                    .addComponent(bajPrimero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(ediIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(ediDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ediDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(ediIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("Carretera");

        jLabel3.setText("Nube");

        jLabel4.setText("Nube ");

        javax.swing.GroupLayout exteriorLayout = new javax.swing.GroupLayout(exterior);
        exterior.setLayout(exteriorLayout);
        exteriorLayout.setHorizontalGroup(
            exteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exteriorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(exteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exteriorLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exteriorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        exteriorLayout.setVerticalGroup(
            exteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exteriorLayout.createSequentialGroup()
                .addGroup(exteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exteriorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(exteriorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(exterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3ActionPerformed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2ActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1ActionPerformed

    private void subBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBActionPerformed

    private void baj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baj1ActionPerformed

    private void baj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baj2ActionPerformed

    private void baj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baj3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baj3ActionPerformed

    private void baj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baj4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baj4ActionPerformed

    private Main prog;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baj1;
    private javax.swing.JButton baj2;
    private javax.swing.JButton baj3;
    private javax.swing.JButton baj4;
    private javax.swing.JLabel bajCuarto;
    private javax.swing.JLabel bajPrimero;
    private javax.swing.JLabel bajSegundo;
    private javax.swing.JLabel bajo;
    private javax.swing.JLabel bajtercero;
    private javax.swing.JPanel ediDer;
    private javax.swing.JPanel ediIzq;
    private javax.swing.JPanel exterior;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel primero;
    private javax.swing.JLabel segundo;
    private javax.swing.JButton sub1;
    private javax.swing.JButton sub2;
    private javax.swing.JButton sub3;
    private javax.swing.JButton subB;
    private javax.swing.JLabel subBajo;
    private javax.swing.JLabel subPrimero;
    private javax.swing.JLabel subSegundo;
    private javax.swing.JLabel subTercero;
    private javax.swing.JLabel tercero;
    // End of variables declaration//GEN-END:variables
}
